language: generic 

sudo: required

services:
    - docker

before_install:
    - docker build -t dinesh1408/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dinesh1408/react-test npm test -- --coverage

after_success:
    - docker build -t dinesh1408/multi-client ./client
    - docker build -t dinesh1408/multi-nginx ./nginx
    - docker build -t dinesh1408/multi-server ./server
    - docker build -t dinesh1408/multi-worker ./worker
    
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Take these images and push to Docker Hub
    - docker push dinesh1407/multi-client
    - docker push dinesh1408/multi-nginx
    - docker push dinesh1408/multi-server
    - docker push dinesh1408/multi-worker
